// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermarketCheckout.DataAccess;

namespace SupermarketCheckout.DataAccess.Migrations
{
    [DbContext(typeof(SupermarketCheckoutContext))]
    [Migration("20190209144703_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("SupermarketCheckout.DataAccess.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Peach"
                        });
                });

            modelBuilder.Entity("SupermarketCheckout.DataAccess.Models.ArticleDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleId");

                    b.Property<decimal>("NewPrice");

                    b.Property<int>("NumberOfArticles");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleDiscounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 2,
                            NewPrice = 130m,
                            NumberOfArticles = 3
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 1,
                            NewPrice = 45m,
                            NumberOfArticles = 2
                        });
                });

            modelBuilder.Entity("SupermarketCheckout.DataAccess.Models.ArticlePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleId");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticlePrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 2,
                            UnitPrice = 50m
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 1,
                            UnitPrice = 30m
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            UnitPrice = 60m
                        });
                });

            modelBuilder.Entity("SupermarketCheckout.DataAccess.Models.ArticleDiscount", b =>
                {
                    b.HasOne("SupermarketCheckout.DataAccess.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SupermarketCheckout.DataAccess.Models.ArticlePrice", b =>
                {
                    b.HasOne("SupermarketCheckout.DataAccess.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
